import {
  UsersThree,
  ChartLineUp,
  FolderSimple,
  CheckSquare,
  Megaphone,
  Browser,
  Palette,
  Code,
  Lifebuoy,
  HardDrives,
} from "@phosphor-icons/react";

export const modules = [
  {
    id: "hr",
    name: "People",
    formal: "HR",
    icon: UsersThree,
    title: "A little less admin. A lot more human.",
    short: "Bring your people and their work together.",
    description:
      "Give people, documents, and everyday processes a clearer place in your business.",
    tasks: ["People & teams", "Leave & onboarding", "Employee documents"],
    category: "Operations",
    number: "01",
    monthlyPrice: 39,
    image: "brand-phone.webp",
  },
  {
    id: "crm",
    name: "Relationships",
    formal: "CRM",
    icon: ChartLineUp,
    title: "Make the next conversation count.",
    short: "Keep relationships moving forward.",
    description:
      "Organize contacts, understand opportunities, and keep the next action in view.",
    tasks: [
      "Contacts & companies",
      "Pipeline visibility",
      "Follow-ups & activities",
    ],
    category: "Growth",
    number: "02",
    monthlyPrice: 49,
    image: "brand-glass.webp",
  },
  {
    id: "files",
    name: "Files",
    formal: "Files",
    icon: FolderSimple,
    title: "Find the file. Keep the flow.",
    short: "Give your business knowledge a home.",
    description:
      "Bring the documents that matter into a clear, shared structure your team can understand.",
    tasks: [
      "Folders & organization",
      "Document discovery",
      "Sharing workflows",
    ],
    category: "Operations",
    number: "03",
    monthlyPrice: 19,
    image: "brand-cards.webp",
  },
  {
    id: "tasks",
    name: "Work",
    formal: "Tasks",
    icon: CheckSquare,
    title: "From a good idea to a job well done.",
    short: "Turn priorities into progress.",
    description:
      "Connect projects, people, and next steps so everyone can see what moves the work forward.",
    tasks: [
      "Project planning",
      "Ownership & priorities",
      "Progress visibility",
    ],
    category: "Operations",
    number: "04",
    monthlyPrice: 25,
    image: "brand-tablet.webp",
  },
  {
    id: "marketing",
    name: "Marketing",
    formal: "Marketing",
    icon: Megaphone,
    title: "Give every campaign a direction.",
    short: "Make your next move more intentional.",
    description:
      "Bring campaign plans, content, and customer activity into a more considered marketing workflow.",
    tasks: ["Campaign planning", "Content calendar", "Performance overview"],
    category: "Growth",
    number: "05",
    monthlyPrice: 35,
    image: "brand-glass.webp",
  },
  {
    id: "website",
    name: "Website",
    formal: "Website Manager",
    icon: Browser,
    title: "Keep your digital front door open.",
    short: "Make your website easier to manage.",
    description:
      "See content, requests, and website priorities together, with a clearer path from update to action.",
    tasks: ["Content management", "Website requests", "Maintenance overview"],
    category: "Growth",
    number: "06",
    monthlyPrice: 29,
    image: "brand-tablet.webp",
  },
];

export const services = [
  {
    title: "Brand & digital design",
    category: "Make it matter",
    icon: Palette,
    text: "From the first impression to the smallest interaction. Identity and experiences built around your audience.",
    tags: ["Brand systems", "Visual identity", "UI/UX design"],
    image: "brand-cards.webp",
    imageAlt: "OrgTik identity applied to a premium business card system",
    caption: "Identity systems, made tangible",
    index: "01",
  },
  {
    title: "Web & app development",
    category: "Make it work",
    icon: Code,
    text: "Translate an ambitious idea into a considered digital experience. Websites and applications with a purpose.",
    tags: ["Web platforms", "Applications", "E-commerce"],
    image: "brand-tablet.webp",
    imageAlt: "OrgTik digital identity displayed on a tablet",
    caption: "Digital experiences with a clear purpose",
    index: "02",
  },
  {
    title: "Marketing & growth",
    category: "Make it move",
    icon: Megaphone,
    text: "Connect your story with the people who need to hear it. A clearer strategy for meaningful attention.",
    tags: ["Campaign strategy", "Search", "Content systems"],
    image: "brand-glass.webp",
    imageAlt: "The OrgTik mark suspended in a sculptural glass form",
    caption: "Attention shaped around a stronger story",
    index: "03",
  },
  {
    title: "IT & ongoing support",
    category: "Keep it moving",
    icon: Lifebuoy,
    text: "A dependable partner for the work after launch. Keep improving the systems your business relies on.",
    tags: ["Website care", "Technical support", "Improvements"],
    image: "brand-phone.webp",
    imageAlt: "OrgTik identity displayed on a mobile device",
    caption: "Ongoing care for the systems behind the work",
    index: "04",
  },
  {
    title: "OrgTik hosting",
    category: "Keep it online",
    icon: HardDrives,
    text: "Reliable hosting shaped for your website, with the performance, monitoring, backups, and support it needs to stay ready.",
    tags: ["Managed hosting", "Monitoring & backups", "Performance care"],
    image: "brand-glass.webp",
    imageAlt: "The OrgTik mark suspended in a sculptural glass form",
    caption: "A dependable home for your digital presence",
    index: "05",
  },
];

export const steps = [
  [
    "Understand",
    "Start with the right questions.",
    "Your business, your people, and what needs to work better.",
  ],
  [
    "Design",
    "Make the way forward clear.",
    "A shared direction, a considered experience, and a practical plan.",
  ],
  [
    "Deliver",
    "Bring the details together.",
    "Design and technology shaped into something people can use.",
  ],
  [
    "Evolve",
    "Keep making it better.",
    "Learn from the work, respond to change, and build on what matters.",
  ],
];
